add_newline = false

[directory]
style = "bold #7AA2F7"  # Blue-ish bright for directory

[battery]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[python]
disabled = true

[character]
success_symbol = "[➜](bold #C0CAF5) "
error_symbol = "[➜](bold #C0CAF5) "
vicmd_symbol = "[➜](bold #C0CAF5) "
